name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 1.3.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  # Plugin for parsing html
  html: ^0.15.0

  # Plugins for parsing css
  csslib: ^0.17.0
  css_colors: ^1.1.0

  # Plugins for rendering the <table> tag.
  flutter_layout_grid: ^1.0.0-nullsafety.5

  # Plugins for rendering the <video> tag.
  # todo remove github dependency
  video_player: ^2.0.0-nullsafety.9
  chewie:
    git:
      url: https://github.com/tneotia/chewie.git
      ref: master

  # Plugin for rendering the <iframe> tag.
  webview_flutter: ^2.0.0-nullsafety.4

  # Plugins for rendering the <audio> tag.
  # todo remove github dependency
  chewie_audio:
    git:
      url: https://github.com/tneotia/chewie_audio.git
      ref: master

  # Plugins for rendering the <svg> tag.
  flutter_svg: ^0.20.0-nullsafety.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

