name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 1.2.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.2.2 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  # Plugin for parsing html
  html: ^0.15.0

  # Plugins for parsing css
  csslib: ^0.17.0
  css_colors: ^1.0.2

  # Plugins for rendering the <table> tag.
  flutter_layout_grid: ^0.11.6

  # Plugins for rendering the <video> tag.
  video_player: ^2.0.0
  chewie: ^1.0.0

  # Plugin for rendering the <iframe> tag.
  webview_flutter: ^2.0.1

  # Plugins for rendering the <audio> tag.
  chewie_audio: 
           git:
              url: https://github.com/nguyenxdat/chewie_audio.git
              ref: master

  # Plugins for rendering the <svg> tag.
  flutter_svg: ^0.19.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

