name: flutter_html
description: A Flutter widget rendering html and css as Flutter widgets.
version: 1.0.0-pre.1
author: Matthew Whitaker <sub6resources@gmail.com>
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: '>=0.7.4'

dependencies:
  html: ^0.14.0+2
  csslib: ^0.16.1
  css_colors: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

